### ISSUE TITLE
Readme

### ISSUE THREAD

**Issue by IzzySoft** [Rudloff/exodus-fdroid#1]
Am I seeing it correctly that exodus-fdroid already ships with exodus-standalone included? If so, you might wish to point that out in the Readme. Got me a little confused :wink:

**Comment by pnu-s** [comment]
Just stepping by here to say that I would advise to use the latest version of exodus-core (1.0.19, I know, exodus-core versions are confusing)

**Comment by Rudloff** [comment]
Thanks for the report, I added a word about this in the README.

> Just stepping by here to say that I would advise to use the latest version of exodus-core (1.0.19, I know, exodus-core versions are confusing)

Hum, does this mean exodus-standalone does not follow [semantic versioning](https://semver.org/)?

I switched to 1.0.15 for now because I have some issue with the dhash dependency on latest releases.

**Comment by IzzySoft** [comment]
For everone looking confused now: Pierre is speaking about the [development branch](https://github.com/Rudloff/exodus-fdroid/tree/develop) where the additions are already visible :wink:

Thanks!

**Comment by pnu-s** [comment]
> Hum, does this mean exodus-standalone does not follow [semantic versioning](https://semver.org/)?

You're right, we don't follow these rules, on none of our projects.
I'll bring the topic within Exodus Privacy and see if we can follow it from now on.
